FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/
COPY data/sprints.json /usr/share/nginx/html/data/sprints.json
RUN mkdir -p /usr/share/nginx/html/data
EXPOSE 80
